services:
  - type: web
    name: privacy-checker
    env: python
    plan: free
    buildCommand: "python -m pip install -r requirements.txt && python -m playwright install --with-deps"
    startCommand: "gunicorn app:app"
